language: python
branches:
  only:
  - master
install:
- pip install pelican ghp-import
script:
- make publish github
env:
  global:
    secure: S6uXCxNRkfkzxnf30tmYUTVmcpTBPKgM5xRwy4vsPYbhgkOXQQQB3IX27+vpJ55qua88AFkEGjzSQ2A9NgwfykLd/3jXCEW+I6HPyrRdI15//plEMS2I5jSXYVI1mi65fmuV+SnlNLyTIV/ywikavLoCg12VA3KHWKfIF5r1eJc=
